### ISSUE TITLE
slnt needs to go 0 to -15

### ISSUE THREAD

**Issue by davelab6** [thundernixon/recursive#50]
The `slnt` axis is currently ranged from `0.0` to `15.0` but sadly https://docs.microsoft.com/en-us/typography/opentype/spec/dvaraxistag_slnt says, 

> Note that the scale for the Slant axis is interpreted as the angle of slant in counter-clockwise degrees from upright. This means that a typical, right-leaning oblique design will have a negative slant value. This matches the scale used for the italicAngle field in the `post` table.

That means the range should be `0.0` to `-15.0`

**Comment by thundernixon** [comment]
Cool, thanks for letting me know! 

This will probably look goofy in slider UIs, but won't be hard to implement in the designspace.

**Comment by thundernixon** [comment]
I'll follow the spec, but this is unfortunate. I think it'll be extremely unintuitive for users to see the default "slant" be `0` and seemingly turned up all the way. 😕

![image](https://user-images.githubusercontent.com/7355414/60601011-50972180-9d7f-11e9-900c-44cd65fe2de4.png)

**Comment by thundernixon** [comment]
(sorry, gif didn't attach properly)

![Kapture 2019-07-03 at 10 44 23](https://user-images.githubusercontent.com/7355414/60601109-8b995500-9d7f-11e9-99a5-1d04b661d8ae.gif)

**Comment by thundernixon** [comment]
Closed by 38fd75f3f
